import { useMemo, useState } from "react";
import type {
  DriftFinding,
  DriftFindingKind,
  DriftReport,
  DriftSeverity,
} from "@tecture/shared";
import { useArchitectureBundle } from "./ArchitectureBundleContext";

const SEVERITY_COLORS: Record<DriftSeverity, string> = {
  error: "#f87171",
  warn: "#fbbf24",
  info: "#38bdf8",
};

const KIND_LABELS: Record<DriftFindingKind, string> = {
  "missing-path": "Missing paths",
  "unverified-edge": "Unverified edges",
  "undeclared-dependency": "Undeclared dependencies",
  "unmapped-external": "Unmapped externals",
  "skipped-node": "Skipped nodes",
  "skipped-edge": "Skipped edges",
};

const KIND_ORDER: DriftFindingKind[] = [
  "missing-path",
  "unverified-edge",
  "undeclared-dependency",
  "unmapped-external",
  "skipped-node",
  "skipped-edge",
];

/** Overall pill color: the most severe finding present wins. */
function overallColor(report: DriftReport): string {
  if (report.summary.errors > 0) return SEVERITY_COLORS.error;
  if (report.summary.warns > 0) return SEVERITY_COLORS.warn;
  return SEVERITY_COLORS.info;
}

/**
 * Drift indicator + findings list, fed by `architecture/.tecture/drift.json`
 * (generated by the architecture-docs skill's evidence script). Hidden
 * entirely when no report or no findings exist.
 */
export function DriftPanel() {
  const bundle = useArchitectureBundle();
  const [open, setOpen] = useState(false);
  const report = bundle.drift;

  const grouped = useMemo(() => {
    if (!report) return [];
    const byKind = new Map<DriftFindingKind, DriftFinding[]>();
    for (const finding of report.findings) {
      const list = byKind.get(finding.kind) ?? [];
      list.push(finding);
      byKind.set(finding.kind, list);
    }
    return KIND_ORDER.filter((k) => byKind.has(k)).map((kind) => ({
      kind,
      findings: byKind.get(kind) ?? [],
    }));
  }, [report]);

  if (!report || report.findings.length === 0) return null;
  const accent = overallColor(report);

  return (
    <div
      className="absolute top-3 left-1/2 z-10 flex -translate-x-1/2 flex-col items-center"
      style={{ fontFamily: "var(--font-mono)" }}
    >
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex items-center gap-2 border px-3 py-1.5 text-[10px] tracking-[0.2em] uppercase shadow-lg backdrop-blur-md transition-colors hover:text-white"
        style={{
          backgroundColor: "rgba(10, 15, 26, 0.85)",
          borderColor: "var(--border-default)",
          color: accent,
        }}
        title="Code-vs-architecture drift findings from the evidence script"
      >
        <span
          className="inline-block h-1.5 w-1.5 rounded-full"
          style={{ backgroundColor: accent }}
        />
        <span>Drift: {report.findings.length}</span>
      </button>

      {open && (
        <div
          className="mt-2 flex flex-col overflow-y-auto border shadow-lg backdrop-blur-md"
          style={{
            width: "min(560px, calc(100vw - 24px))",
            maxHeight: "min(480px, calc(100vh - 96px))",
            backgroundColor: "rgba(10, 15, 26, 0.9)",
            borderColor: "var(--border-default)",
          }}
        >
          <div
            className="flex items-center justify-between border-b px-4 py-2 text-[10px]"
            style={{
              borderColor: "var(--border-default)",
              color: "var(--text-muted)",
            }}
          >
            <span>
              generated {formatTimestamp(report.generatedAt)} · codegraph schema v
              {report.codegraphSchemaVersion}
            </span>
            <span>
              {report.summary.errors} err / {report.summary.warns} warn /{" "}
              {report.summary.infos} info
            </span>
          </div>

          {report.staleIndex && (
            <div
              className="border-b px-4 py-2 text-[11px]"
              style={{
                borderColor: "var(--border-default)",
                color: SEVERITY_COLORS.warn,
              }}
            >
              Index may be stale — files changed after the last CodeGraph sync.
              Run <code>codegraph sync</code> and re-run the evidence script.
            </div>
          )}

          <div className="flex flex-col gap-3 px-4 py-3">
            {grouped.map(({ kind, findings }) => (
              <div key={kind} className="flex flex-col gap-1.5">
                <div
                  className="text-[9px] tracking-[0.25em] uppercase"
                  style={{ color: "var(--text-muted)" }}
                >
                  {KIND_LABELS[kind]} ({findings.length})
                </div>
                {findings.map((finding, i) => (
                  <FindingRow key={`${kind}-${i}`} finding={finding} />
                ))}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function FindingRow({ finding }: { finding: DriftFinding }) {
  const color = SEVERITY_COLORS[finding.severity];
  const where =
    finding.nodeId ??
    (finding.edge
      ? `${finding.edge.sourceId} → ${finding.edge.targetId}`
      : finding.evidence?.package);
  return (
    <div className="flex items-start gap-2 text-[11px] leading-snug">
      <span
        className="mt-1 inline-block h-1.5 w-1.5 shrink-0 rounded-full"
        style={{ backgroundColor: color }}
        title={finding.severity}
      />
      <span style={{ color: "var(--text-primary, #e2e8f0)" }}>
        {where ? (
          <span className="mr-1.5" style={{ color }}>
            {where}
          </span>
        ) : null}
        {finding.message}
        {finding.evidence?.edgeKinds ? (
          <span className="ml-1.5" style={{ color: "var(--text-muted)" }}>
            (
            {Object.entries(finding.evidence.edgeKinds)
              .map(([k, n]) => `${k}:${n}`)
              .join(", ")}
            )
          </span>
        ) : null}
      </span>
    </div>
  );
}

function formatTimestamp(iso: string): string {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return iso;
  return new Date(t).toLocaleString();
}
